# Generated by Django 3.2.5 on 2021-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_time', models.DateTimeField()),
                ('referenced_time', models.DateTimeField()),
                ('currency', models.CharField(max_length=64)),
                ('current_exchange_rate', models.FloatField()),
                ('referenced_exchange_rate', models.FloatField()),
                ('published', models.BooleanField()),
                ('declined', models.BooleanField()),
            ],
        ),
    ]
