# Generated by Django 3.2.5 on 2021-10-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
