# Generated by Django 3.2.5 on 2022-01-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0005_alert_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='published_text',
            field=models.TextField(blank=True),
        ),
    ]
